environment:
  matrix:
    - nodejs_version: 4
    - nodejs_version: 6
    - nodejs_version: 7

platform:
  - x86
  - x64

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install -g npm codecov
  - npm install

# Post-install test scripts.
test_script:
  - node --version
  - npm --version
  - npm test

# Don't actually build.
build: off
